### ISSUE TITLE
Why is the tests for mac-os workflow failing?

### ISSUE THREAD

**Issue by blaylockbk** [blaylockbk/Herbie#310]
Seems like something changed upstream. I haven't had this issue before.

https://github.com/blaylockbk/Herbie/actions/runs/8934289366/job/24541529029

**Comment by blaylockbk** [comment]
What I found

- https://stackoverflow.com/questions/75602063/pip-install-r-requirements-txt-is-failing-this-environment-is-externally-mana
- https://github.com/actions/runner-images/issues/8615

**Comment by blaylockbk** [comment]
Adding `--break-system-packages` in my workflow for macOS seemed to work

```yaml
      - name: Install project (macOS)
        if: runner.os == 'macOS'
        run: |
          pip3 install --break-system-packages --requirement=requirements-test.txt
          pip3 install --break-system-packages --editable=.
```
