### ISSUE TITLE
Docs: Restore my original header color (for light theme)

### ISSUE THREAD

**Issue by blaylockbk** [blaylockbk/Herbie#80]
The new PyData Sphinx dark theme is awesome! But how do I restore the header color? The header banner background is now white instead of tan
![image](https://user-images.githubusercontent.com/6249613/172959133-d7cbae54-20d3-49ed-91a2-722031e23026.png)

https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/customizing.html?highlight=css#customize-the-css-of-light-and-dark-themes

This didn't seem to help:
```css
.bd-header[data-theme="light"] {
    background-color: #f0ead2 !important;
}

a:-webkit-any-link[data-theme="light"] {
    color: #25529b !important;
}

```
